services:
  frontend:
    container_name: angularfrontend
    image: borheneddinebenattia/foyerdevopsfront:latest
  
  backend:
    container_name: springbackend
    image: borheneddinebenattia/foyerdevopsbackend:latest
    
  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
